//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uno.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uno.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_back {
            get {
                object obj = ResourceManager.GetObject("card_back", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_0 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_1 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_2 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_3 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_4 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_5 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_6 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_7 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_8 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_9 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_draw {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_draw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_reverse {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_reverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_blue_skip {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_blue_skip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_0 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_1 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_2 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_3 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_4 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_5 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_6 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_7 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_8 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_9 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_draw {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_draw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_reverse {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_reverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_green_skip {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_green_skip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_0 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_1 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_2 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_3 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_4 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_5 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_6 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_7 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_8 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_9 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_draw {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_draw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_reverse {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_reverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_red_skip {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_red_skip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_0 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_1 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_2 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_3 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_4 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_5 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_6 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_7 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_8 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_9 {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_draw {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_draw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_reverse {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_reverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_suit_yellow_skip {
            get {
                object obj = ResourceManager.GetObject("card_front_suit_yellow_skip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_wild_pickup {
            get {
                object obj = ResourceManager.GetObject("card_front_wild_pickup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] card_front_wild_standard {
            get {
                object obj = ResourceManager.GetObject("card_front_wild_standard", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
